// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { Metadata, Endpoint, HandlerFunction } from './types';

export { Metadata, Endpoint, HandlerFunction };

import get_allegro_prices_account_eligibility_sale from './sale/get-allegro-prices-account-eligibility-sale';
import get_badge_campaigns_sale from './sale/get-badge-campaigns-sale';
import get_badge_operation_details_sale from './sale/get-badge-operation-details-sale';
import get_category_events_sale from './sale/get-category-events-sale';
import get_category_parameters_scheduled_changes_sale from './sale/get-category-parameters-scheduled-changes-sale';
import get_classified_offers_stats_sale from './sale/get-classified-offers-stats-sale';
import get_classified_seller_stats_sale from './sale/get-classified-seller-stats-sale';
import get_compatibility_list_suggestions_sale from './sale/get-compatibility-list-suggestions-sale';
import get_delivery_methods_sale from './sale/get-delivery-methods-sale';
import get_matching_categories_sale from './sale/get-matching-categories-sale';
import get_offer_events_sale from './sale/get-offer-events-sale';
import get_offer_promotion_packages_sale from './sale/get-offer-promotion-packages-sale';
import get_quality_sale from './sale/get-quality-sale';
import get_size_tables_templates_sale from './sale/get-size-tables-templates-sale';
import get_smart_seller_classification_report_sale from './sale/get-smart-seller-classification-report-sale';
import get_tax_settings_sale from './sale/get-tax-settings-sale';
import propose_product_sale from './sale/propose-product-sale';
import update_allegro_prices_account_consent_sale from './sale/update-allegro-prices-account-consent-sale';
import upload_image_sale from './sale/upload-image-sale';
import create_sale_product_offers from './sale/product-offers/create-sale-product-offers';
import retrieve_sale_product_offers from './sale/product-offers/retrieve-sale-product-offers';
import update_sale_product_offers from './sale/product-offers/update-sale-product-offers';
import check_operation_status_sale_product_offers from './sale/product-offers/check-operation-status-sale-product-offers';
import retrieve_parts_sale_product_offers from './sale/product-offers/retrieve-parts-sale-product-offers';
import list_sale_offers from './sale/offers/list-sale-offers';
import delete_sale_offers from './sale/offers/delete-sale-offers';
import list_unfilled_parameters_sale_offers from './sale/offers/list-unfilled-parameters-sale-offers';
import modify_promo_options_sale_offers from './sale/offers/modify-promo-options-sale-offers';
import retrieve_rating_sale_offers from './sale/offers/retrieve-rating-sale-offers';
import retrieve_smart_report_sale_offers from './sale/offers/retrieve-smart-report-sale-offers';
import update_offers_sale_translations from './sale/offers/translations/update-offers-sale-translations';
import list_offers_sale_translations from './sale/offers/translations/list-offers-sale-translations';
import delete_offers_sale_translations from './sale/offers/translations/delete-offers-sale-translations';
import list_offers_sale_promo_options from './sale/offers/promo-options/list-offers-sale-promo-options';
import get_all_offers_sale_promo_options from './sale/offers/promo-options/get-all-offers-sale-promo-options';
import batch_modify_offers_sale_promo_options_commands from './sale/offers/promo-options-commands/batch-modify-offers-sale-promo-options-commands';
import detailed_result_offers_sale_promo_options_commands from './sale/offers/promo-options-commands/detailed-result-offers-sale-promo-options-commands';
import summary_offers_sale_promo_options_commands from './sale/offers/promo-options-commands/summary-offers-sale-promo-options-commands';
import create_offers_sale_tags from './sale/offers/tags/create-offers-sale-tags';
import update_offers_sale_tags from './sale/offers/tags/update-offers-sale-tags';
import delete_offers_sale_tags from './sale/offers/tags/delete-offers-sale-tags';
import assign_offers_sale_tags from './sale/offers/tags/assign-offers-sale-tags';
import list_0_offers_sale_tags from './sale/offers/tags/list-0-offers-sale-tags';
import list_1_offers_sale_tags from './sale/offers/tags/list-1-offers-sale-tags';
import batch_modify_sale_offer_publication_commands from './sale/offer-publication-commands/batch-modify-sale-offer-publication-commands';
import get_detailed_report_sale_offer_publication_commands from './sale/offer-publication-commands/get-detailed-report-sale-offer-publication-commands';
import get_summary_sale_offer_publication_commands from './sale/offer-publication-commands/get-summary-sale-offer-publication-commands';
import retrieve_sale_offer_classifieds_packages from './sale/offer-classifieds-packages/retrieve-sale-offer-classifieds-packages';
import update_sale_offer_classifieds_packages from './sale/offer-classifieds-packages/update-sale-offer-classifieds-packages';
import retrieve_sale_classifieds_packages from './sale/classifieds-packages/retrieve-sale-classifieds-packages';
import list_sale_classifieds_packages from './sale/classifieds-packages/list-sale-classifieds-packages';
import retrieve_sale_user_ratings from './sale/user-ratings/retrieve-sale-user-ratings';
import list_sale_user_ratings from './sale/user-ratings/list-sale-user-ratings';
import answer_sale_user_ratings from './sale/user-ratings/answer-sale-user-ratings';
import request_removal_sale_user_ratings from './sale/user-ratings/request-removal-sale-user-ratings';
import get_categories_sale_offer_additional_services from './sale/offer-additional-services/get-categories-sale-offer-additional-services';
import create_offer_additional_services_sale_groups from './sale/offer-additional-services/groups/create-offer-additional-services-sale-groups';
import retrieve_offer_additional_services_sale_groups from './sale/offer-additional-services/groups/retrieve-offer-additional-services-sale-groups';
import update_offer_additional_services_sale_groups from './sale/offer-additional-services/groups/update-offer-additional-services-sale-groups';
import list_offer_additional_services_sale_groups from './sale/offer-additional-services/groups/list-offer-additional-services-sale-groups';
import update_groups_offer_additional_services_sale_translations from './sale/offer-additional-services/groups/translations/update-groups-offer-additional-services-sale-translations';
import list_groups_offer_additional_services_sale_translations from './sale/offer-additional-services/groups/translations/list-groups-offer-additional-services-sale-translations';
import delete_groups_offer_additional_services_sale_translations from './sale/offer-additional-services/groups/translations/delete-groups-offer-additional-services-sale-translations';
import create_sale_bundles from './sale/bundles/create-sale-bundles';
import retrieve_sale_bundles from './sale/bundles/retrieve-sale-bundles';
import list_sale_bundles from './sale/bundles/list-sale-bundles';
import delete_sale_bundles from './sale/bundles/delete-sale-bundles';
import update_discount_sale_bundles from './sale/bundles/update-discount-sale-bundles';
import create_loyalty_sale_promotions from './sale/loyalty/promotions/create-loyalty-sale-promotions';
import retrieve_loyalty_sale_promotions from './sale/loyalty/promotions/retrieve-loyalty-sale-promotions';
import update_loyalty_sale_promotions from './sale/loyalty/promotions/update-loyalty-sale-promotions';
import list_loyalty_sale_promotions from './sale/loyalty/promotions/list-loyalty-sale-promotions';
import delete_loyalty_sale_promotions from './sale/loyalty/promotions/delete-loyalty-sale-promotions';
import update_sale_turnover_discount from './sale/turnover-discount/update-sale-turnover-discount';
import list_sale_turnover_discount from './sale/turnover-discount/list-sale-turnover-discount';
import deactivate_sale_turnover_discount from './sale/turnover-discount/deactivate-sale-turnover-discount';
import retrieve_sale_offer_modification_commands from './sale/offer-modification-commands/retrieve-sale-offer-modification-commands';
import update_sale_offer_modification_commands from './sale/offer-modification-commands/update-sale-offer-modification-commands';
import tasks_sale_offer_modification_commands from './sale/offer-modification-commands/tasks-sale-offer-modification-commands';
import retrieve_sale_offer_price_change_commands from './sale/offer-price-change-commands/retrieve-sale-offer-price-change-commands';
import update_sale_offer_price_change_commands from './sale/offer-price-change-commands/update-sale-offer-price-change-commands';
import tasks_sale_offer_price_change_commands from './sale/offer-price-change-commands/tasks-sale-offer-price-change-commands';
import retrieve_sale_offer_quantity_change_commands from './sale/offer-quantity-change-commands/retrieve-sale-offer-quantity-change-commands';
import update_sale_offer_quantity_change_commands from './sale/offer-quantity-change-commands/update-sale-offer-quantity-change-commands';
import tasks_sale_offer_quantity_change_commands from './sale/offer-quantity-change-commands/tasks-sale-offer-quantity-change-commands';
import create_sale_offer_price_automation_commands from './sale/offer-price-automation-commands/create-sale-offer-price-automation-commands';
import retrieve_sale_offer_price_automation_commands from './sale/offer-price-automation-commands/retrieve-sale-offer-price-automation-commands';
import tasks_sale_offer_price_automation_commands from './sale/offer-price-automation-commands/tasks-sale-offer-price-automation-commands';
import create_price_automation_sale_rules from './sale/price-automation/rules/create-price-automation-sale-rules';
import retrieve_price_automation_sale_rules from './sale/price-automation/rules/retrieve-price-automation-sale-rules';
import update_price_automation_sale_rules from './sale/price-automation/rules/update-price-automation-sale-rules';
import list_price_automation_sale_rules from './sale/price-automation/rules/list-price-automation-sale-rules';
import delete_price_automation_sale_rules from './sale/price-automation/rules/delete-price-automation-sale-rules';
import retrieve_rules_price_automation_sale_offers from './sale/price-automation/offers/retrieve-rules-price-automation-sale-offers';
import retrieve_sale_categories from './sale/categories/retrieve-sale-categories';
import list_sale_categories from './sale/categories/list-sale-categories';
import retrieve_parameters_sale_categories from './sale/categories/retrieve-parameters-sale-categories';
import retrieve_product_parameters_sale_categories from './sale/categories/retrieve-product-parameters-sale-categories';
import create_sale_shipping_rates from './sale/shipping-rates/create-sale-shipping-rates';
import retrieve_sale_shipping_rates from './sale/shipping-rates/retrieve-sale-shipping-rates';
import update_sale_shipping_rates from './sale/shipping-rates/update-sale-shipping-rates';
import list_sale_shipping_rates from './sale/shipping-rates/list-sale-shipping-rates';
import retrieve_sale_delivery_settings from './sale/delivery-settings/retrieve-sale-delivery-settings';
import update_sale_delivery_settings from './sale/delivery-settings/update-sale-delivery-settings';
import create_sale_offer_contacts from './sale/offer-contacts/create-sale-offer-contacts';
import retrieve_sale_offer_contacts from './sale/offer-contacts/retrieve-sale-offer-contacts';
import update_sale_offer_contacts from './sale/offer-contacts/update-sale-offer-contacts';
import list_sale_offer_contacts from './sale/offer-contacts/list-sale-offer-contacts';
import create_sale_responsible_persons from './sale/responsible-persons/create-sale-responsible-persons';
import update_sale_responsible_persons from './sale/responsible-persons/update-sale-responsible-persons';
import list_sale_responsible_persons from './sale/responsible-persons/list-sale-responsible-persons';
import create_sale_responsible_producers from './sale/responsible-producers/create-sale-responsible-producers';
import retrieve_sale_responsible_producers from './sale/responsible-producers/retrieve-sale-responsible-producers';
import update_sale_responsible_producers from './sale/responsible-producers/update-sale-responsible-producers';
import list_sale_responsible_producers from './sale/responsible-producers/list-sale-responsible-producers';
import create_sale_size_tables from './sale/size-tables/create-sale-size-tables';
import retrieve_sale_size_tables from './sale/size-tables/retrieve-sale-size-tables';
import update_sale_size_tables from './sale/size-tables/update-sale-size-tables';
import list_sale_size_tables from './sale/size-tables/list-sale-size-tables';
import create_sale_offer_variants from './sale/offer-variants/create-sale-offer-variants';
import retrieve_sale_offer_variants from './sale/offer-variants/retrieve-sale-offer-variants';
import update_sale_offer_variants from './sale/offer-variants/update-sale-offer-variants';
import list_sale_offer_variants from './sale/offer-variants/list-sale-offer-variants';
import delete_sale_offer_variants from './sale/offer-variants/delete-sale-offer-variants';
import create_sale_offer_attachments from './sale/offer-attachments/create-sale-offer-attachments';
import retrieve_sale_offer_attachments from './sale/offer-attachments/retrieve-sale-offer-attachments';
import upload_sale_offer_attachments from './sale/offer-attachments/upload-sale-offer-attachments';
import retrieve_sale_disputes from './sale/disputes/retrieve-sale-disputes';
import list_sale_disputes from './sale/disputes/list-sale-disputes';
import create_disputes_sale_messages from './sale/disputes/messages/create-disputes-sale-messages';
import list_disputes_sale_messages from './sale/disputes/messages/list-disputes-sale-messages';
import create_sale_dispute_attachments from './sale/dispute-attachments/create-sale-dispute-attachments';
import retrieve_sale_dispute_attachments from './sale/dispute-attachments/retrieve-sale-dispute-attachments';
import upload_sale_dispute_attachments from './sale/dispute-attachments/upload-sale-dispute-attachments';
import retrieve_sale_products from './sale/products/retrieve-sale-products';
import list_sale_products from './sale/products/list-sale-products';
import create_products_sale_change_proposals from './sale/products/change-proposals/create-products-sale-change-proposals';
import retrieve_products_sale_change_proposals from './sale/products/change-proposals/retrieve-products-sale-change-proposals';
import list_sale_compatibility_list from './sale/compatibility-list/list-sale-compatibility-list';
import list_sale_compatible_products from './sale/compatible-products/list-sale-compatible-products';
import list_groups_sale_compatible_products from './sale/compatible-products/list-groups-sale-compatible-products';
import list_sale_badges from './sale/badges/list-sale-badges';
import apply_sale_badges from './sale/badges/apply-sale-badges';
import update_campaign_badges_sale_offers from './sale/badges/offers/update-campaign-badges-sale-offers';
import retrieve_sale_badge_applications from './sale/badge-applications/retrieve-sale-badge-applications';
import list_sale_badge_applications from './sale/badge-applications/list-sale-badge-applications';
import retrieve_sale_allegro_prices_offer_consents from './sale/allegro-prices-offer-consents/retrieve-sale-allegro-prices-offer-consents';
import update_sale_allegro_prices_offer_consents from './sale/allegro-prices-offer-consents/update-sale-allegro-prices-offer-consents';
import list_campaigns_sale_alle_discount from './sale/alle-discount/list-campaigns-sale-alle-discount';
import list_eligible_offers_sale_alle_discount from './sale/alle-discount/list-eligible-offers-sale-alle-discount';
import list_submitted_offers_sale_alle_discount from './sale/alle-discount/list-submitted-offers-sale-alle-discount';
import create_alle_discount_sale_submit_offer_commands from './sale/alle-discount/submit-offer-commands/create-alle-discount-sale-submit-offer-commands';
import retrieve_alle_discount_sale_submit_offer_commands from './sale/alle-discount/submit-offer-commands/retrieve-alle-discount-sale-submit-offer-commands';
import create_alle_discount_sale_withdraw_offer_commands from './sale/alle-discount/withdraw-offer-commands/create-alle-discount-sale-withdraw-offer-commands';
import retrieve_alle_discount_sale_withdraw_offer_commands from './sale/alle-discount/withdraw-offer-commands/retrieve-alle-discount-sale-withdraw-offer-commands';
import list_offers from './offers/list-offers';
import change_price_offers from './offers/change-price-offers';
import retrieve_ratings_summary_users from './users/retrieve-ratings-summary-users';
import retrieve_me from './me/retrieve-me';
import calculate_fee_preview_pricing from './pricing/calculate-fee-preview-pricing';
import get_offer_quotes_pricing from './pricing/get-offer-quotes-pricing';
import create_points_of_service from './points-of-service/create-points-of-service';
import retrieve_points_of_service from './points-of-service/retrieve-points-of-service';
import update_points_of_service from './points-of-service/update-points-of-service';
import list_points_of_service from './points-of-service/list-points-of-service';
import delete_points_of_service from './points-of-service/delete-points-of-service';
import create_after_sales_service_conditions_return_policies from './after-sales-service-conditions/return-policies/create-after-sales-service-conditions-return-policies';
import retrieve_after_sales_service_conditions_return_policies from './after-sales-service-conditions/return-policies/retrieve-after-sales-service-conditions-return-policies';
import update_after_sales_service_conditions_return_policies from './after-sales-service-conditions/return-policies/update-after-sales-service-conditions-return-policies';
import list_after_sales_service_conditions_return_policies from './after-sales-service-conditions/return-policies/list-after-sales-service-conditions-return-policies';
import delete_after_sales_service_conditions_return_policies from './after-sales-service-conditions/return-policies/delete-after-sales-service-conditions-return-policies';
import create_after_sales_service_conditions_implied_warranties from './after-sales-service-conditions/implied-warranties/create-after-sales-service-conditions-implied-warranties';
import retrieve_after_sales_service_conditions_implied_warranties from './after-sales-service-conditions/implied-warranties/retrieve-after-sales-service-conditions-implied-warranties';
import update_after_sales_service_conditions_implied_warranties from './after-sales-service-conditions/implied-warranties/update-after-sales-service-conditions-implied-warranties';
import list_after_sales_service_conditions_implied_warranties from './after-sales-service-conditions/implied-warranties/list-after-sales-service-conditions-implied-warranties';
import create_after_sales_service_conditions_warranties from './after-sales-service-conditions/warranties/create-after-sales-service-conditions-warranties';
import retrieve_after_sales_service_conditions_warranties from './after-sales-service-conditions/warranties/retrieve-after-sales-service-conditions-warranties';
import update_after_sales_service_conditions_warranties from './after-sales-service-conditions/warranties/update-after-sales-service-conditions-warranties';
import list_after_sales_service_conditions_warranties from './after-sales-service-conditions/warranties/list-after-sales-service-conditions-warranties';
import create_after_sales_service_conditions_attachments from './after-sales-service-conditions/attachments/create-after-sales-service-conditions-attachments';
import upload_after_sales_service_conditions_attachments from './after-sales-service-conditions/attachments/upload-after-sales-service-conditions-attachments';
import get_event_stats_order from './order/get-event-stats-order';
import list_events_order from './order/list-events-order';
import retrieve_order_checkout_forms from './order/checkout-forms/retrieve-order-checkout-forms';
import list_order_checkout_forms from './order/checkout-forms/list-order-checkout-forms';
import update_fulfillment_order_checkout_forms from './order/checkout-forms/update-fulfillment-order-checkout-forms';
import list_checkout_forms_order_shipments from './order/checkout-forms/shipments/list-checkout-forms-order-shipments';
import add_checkout_forms_order_shipments from './order/checkout-forms/shipments/add-checkout-forms-order-shipments';
import create_checkout_forms_order_invoices from './order/checkout-forms/invoices/create-checkout-forms-order-invoices';
import list_checkout_forms_order_invoices from './order/checkout-forms/invoices/list-checkout-forms-order-invoices';
import upload_file_checkout_forms_order_invoices from './order/checkout-forms/invoices/upload-file-checkout-forms-order-invoices';
import list_order_carriers from './order/carriers/list-order-carriers';
import get_tracking_order_carriers from './order/carriers/get-tracking-order-carriers';
import list_points_carriers_order_allegro from './order/carriers/allegro/list-points-carriers-order-allegro';
import create_order_refund_claims from './order/refund-claims/create-order-refund-claims';
import retrieve_order_refund_claims from './order/refund-claims/retrieve-order-refund-claims';
import list_order_refund_claims from './order/refund-claims/list-order-refund-claims';
import cancel_order_refund_claims from './order/refund-claims/cancel-order-refund-claims';
import retrieve_order_customer_returns from './order/customer-returns/retrieve-order-customer-returns';
import list_order_customer_returns from './order/customer-returns/list-order-customer-returns';
import reject_refund_order_customer_returns from './order/customer-returns/reject-refund-order-customer-returns';
import create_account_additional_emails from './account/additional-emails/create-account-additional-emails';
import retrieve_account_additional_emails from './account/additional-emails/retrieve-account-additional-emails';
import list_account_additional_emails from './account/additional-emails/list-account-additional-emails';
import delete_account_additional_emails from './account/additional-emails/delete-account-additional-emails';
import list_operations_payments from './payments/list-operations-payments';
import create_payments_refunds from './payments/refunds/create-payments-refunds';
import list_payments_refunds from './payments/refunds/list-payments-refunds';
import retrieve_offers_bidding_bid from './bidding/offers/bid/retrieve-offers-bidding-bid';
import place_offers_bidding_bid from './bidding/offers/bid/place-offers-bidding-bid';
import list_billing_entries_billing from './billing/list-billing-entries-billing';
import list_billing_types_billing from './billing/list-billing-types-billing';
import list_fundraising_campaigns_charity from './charity/list-fundraising-campaigns-charity';
import create_label_shipment_management from './shipment-management/create-label-shipment-management';
import create_protocol_shipment_management from './shipment-management/create-protocol-shipment-management';
import list_delivery_services_shipment_management from './shipment-management/list-delivery-services-shipment-management';
import list_pickup_proposals_shipment_management from './shipment-management/list-pickup-proposals-shipment-management';
import retrieve_shipment_management_shipments from './shipment-management/shipments/retrieve-shipment-management-shipments';
import create_shipments_shipment_management_create_commands from './shipment-management/shipments/create-commands/create-shipments-shipment-management-create-commands';
import get_status_shipments_shipment_management_create_commands from './shipment-management/shipments/create-commands/get-status-shipments-shipment-management-create-commands';
import cancel_shipments_shipment_management_cancel_commands from './shipment-management/shipments/cancel-commands/cancel-shipments-shipment-management-cancel-commands';
import get_status_shipments_shipment_management_cancel_commands from './shipment-management/shipments/cancel-commands/get-status-shipments-shipment-management-cancel-commands';
import get_status_pickups_shipment_management_create_commands from './shipment-management/pickups/create-commands/get-status-pickups-shipment-management-create-commands';
import request_pickup_pickups_shipment_management_create_commands from './shipment-management/pickups/create-commands/request-pickup-pickups-shipment-management-create-commands';
import list_marketplaces from './marketplaces/list-marketplaces';
import retrieve_messaging_threads from './messaging/threads/retrieve-messaging-threads';
import list_messaging_threads from './messaging/threads/list-messaging-threads';
import mark_as_read_messaging_threads from './messaging/threads/mark-as-read-messaging-threads';
import create_threads_messaging_messages from './messaging/threads/messages/create-threads-messaging-messages';
import list_threads_messaging_messages from './messaging/threads/messages/list-threads-messaging-messages';
import create_messaging_messages from './messaging/messages/create-messaging-messages';
import retrieve_messaging_messages from './messaging/messages/retrieve-messaging-messages';
import delete_messaging_messages from './messaging/messages/delete-messaging-messages';
import create_messaging_message_attachments from './messaging/message-attachments/create-messaging-message-attachments';
import download_messaging_message_attachments from './messaging/message-attachments/download-messaging-message-attachments';
import upload_messaging_message_attachments from './messaging/message-attachments/upload-messaging-message-attachments';
import get_available_products_fulfillment from './fulfillment/get-available-products-fulfillment';
import get_stock_fulfillment from './fulfillment/get-stock-fulfillment';
import create_fulfillment_advance_ship_notices from './fulfillment/advance-ship-notices/create-fulfillment-advance-ship-notices';
import retrieve_fulfillment_advance_ship_notices from './fulfillment/advance-ship-notices/retrieve-fulfillment-advance-ship-notices';
import update_fulfillment_advance_ship_notices from './fulfillment/advance-ship-notices/update-fulfillment-advance-ship-notices';
import list_fulfillment_advance_ship_notices from './fulfillment/advance-ship-notices/list-fulfillment-advance-ship-notices';
import delete_fulfillment_advance_ship_notices from './fulfillment/advance-ship-notices/delete-fulfillment-advance-ship-notices';
import cancel_fulfillment_advance_ship_notices from './fulfillment/advance-ship-notices/cancel-fulfillment-advance-ship-notices';
import get_labels_fulfillment_advance_ship_notices from './fulfillment/advance-ship-notices/get-labels-fulfillment-advance-ship-notices';
import get_receiving_state_fulfillment_advance_ship_notices from './fulfillment/advance-ship-notices/get-receiving-state-fulfillment-advance-ship-notices';
import update_submitted_fulfillment_advance_ship_notices from './fulfillment/advance-ship-notices/update-submitted-fulfillment-advance-ship-notices';
import get_status_fulfillment_submit_commands from './fulfillment/submit-commands/get-status-fulfillment-submit-commands';
import submit_fulfillment_submit_commands from './fulfillment/submit-commands/submit-fulfillment-submit-commands';
import get_parcels_fulfillment_orders from './fulfillment/orders/get-parcels-fulfillment-orders';
import update_fulfillment_tax_id from './fulfillment/tax-id/update-fulfillment-tax-id';
import add_fulfillment_tax_id from './fulfillment/tax-id/add-fulfillment-tax-id';
import get_fulfillment_tax_id from './fulfillment/tax-id/get-fulfillment-tax-id';
import create_removal_fulfillment_preferences from './fulfillment/removal/preferences/create-removal-fulfillment-preferences';
import get_removal_fulfillment_preferences from './fulfillment/removal/preferences/get-removal-fulfillment-preferences';

export const endpoints: Endpoint[] = [];

function addEndpoint(endpoint: Endpoint) {
  endpoints.push(endpoint);
}

addEndpoint(get_allegro_prices_account_eligibility_sale);
addEndpoint(get_badge_campaigns_sale);
addEndpoint(get_badge_operation_details_sale);
addEndpoint(get_category_events_sale);
addEndpoint(get_category_parameters_scheduled_changes_sale);
addEndpoint(get_classified_offers_stats_sale);
addEndpoint(get_classified_seller_stats_sale);
addEndpoint(get_compatibility_list_suggestions_sale);
addEndpoint(get_delivery_methods_sale);
addEndpoint(get_matching_categories_sale);
addEndpoint(get_offer_events_sale);
addEndpoint(get_offer_promotion_packages_sale);
addEndpoint(get_quality_sale);
addEndpoint(get_size_tables_templates_sale);
addEndpoint(get_smart_seller_classification_report_sale);
addEndpoint(get_tax_settings_sale);
addEndpoint(propose_product_sale);
addEndpoint(update_allegro_prices_account_consent_sale);
addEndpoint(upload_image_sale);
addEndpoint(create_sale_product_offers);
addEndpoint(retrieve_sale_product_offers);
addEndpoint(update_sale_product_offers);
addEndpoint(check_operation_status_sale_product_offers);
addEndpoint(retrieve_parts_sale_product_offers);
addEndpoint(list_sale_offers);
addEndpoint(delete_sale_offers);
addEndpoint(list_unfilled_parameters_sale_offers);
addEndpoint(modify_promo_options_sale_offers);
addEndpoint(retrieve_rating_sale_offers);
addEndpoint(retrieve_smart_report_sale_offers);
addEndpoint(update_offers_sale_translations);
addEndpoint(list_offers_sale_translations);
addEndpoint(delete_offers_sale_translations);
addEndpoint(list_offers_sale_promo_options);
addEndpoint(get_all_offers_sale_promo_options);
addEndpoint(batch_modify_offers_sale_promo_options_commands);
addEndpoint(detailed_result_offers_sale_promo_options_commands);
addEndpoint(summary_offers_sale_promo_options_commands);
addEndpoint(create_offers_sale_tags);
addEndpoint(update_offers_sale_tags);
addEndpoint(delete_offers_sale_tags);
addEndpoint(assign_offers_sale_tags);
addEndpoint(list_0_offers_sale_tags);
addEndpoint(list_1_offers_sale_tags);
addEndpoint(batch_modify_sale_offer_publication_commands);
addEndpoint(get_detailed_report_sale_offer_publication_commands);
addEndpoint(get_summary_sale_offer_publication_commands);
addEndpoint(retrieve_sale_offer_classifieds_packages);
addEndpoint(update_sale_offer_classifieds_packages);
addEndpoint(retrieve_sale_classifieds_packages);
addEndpoint(list_sale_classifieds_packages);
addEndpoint(retrieve_sale_user_ratings);
addEndpoint(list_sale_user_ratings);
addEndpoint(answer_sale_user_ratings);
addEndpoint(request_removal_sale_user_ratings);
addEndpoint(get_categories_sale_offer_additional_services);
addEndpoint(create_offer_additional_services_sale_groups);
addEndpoint(retrieve_offer_additional_services_sale_groups);
addEndpoint(update_offer_additional_services_sale_groups);
addEndpoint(list_offer_additional_services_sale_groups);
addEndpoint(update_groups_offer_additional_services_sale_translations);
addEndpoint(list_groups_offer_additional_services_sale_translations);
addEndpoint(delete_groups_offer_additional_services_sale_translations);
addEndpoint(create_sale_bundles);
addEndpoint(retrieve_sale_bundles);
addEndpoint(list_sale_bundles);
addEndpoint(delete_sale_bundles);
addEndpoint(update_discount_sale_bundles);
addEndpoint(create_loyalty_sale_promotions);
addEndpoint(retrieve_loyalty_sale_promotions);
addEndpoint(update_loyalty_sale_promotions);
addEndpoint(list_loyalty_sale_promotions);
addEndpoint(delete_loyalty_sale_promotions);
addEndpoint(update_sale_turnover_discount);
addEndpoint(list_sale_turnover_discount);
addEndpoint(deactivate_sale_turnover_discount);
addEndpoint(retrieve_sale_offer_modification_commands);
addEndpoint(update_sale_offer_modification_commands);
addEndpoint(tasks_sale_offer_modification_commands);
addEndpoint(retrieve_sale_offer_price_change_commands);
addEndpoint(update_sale_offer_price_change_commands);
addEndpoint(tasks_sale_offer_price_change_commands);
addEndpoint(retrieve_sale_offer_quantity_change_commands);
addEndpoint(update_sale_offer_quantity_change_commands);
addEndpoint(tasks_sale_offer_quantity_change_commands);
addEndpoint(create_sale_offer_price_automation_commands);
addEndpoint(retrieve_sale_offer_price_automation_commands);
addEndpoint(tasks_sale_offer_price_automation_commands);
addEndpoint(create_price_automation_sale_rules);
addEndpoint(retrieve_price_automation_sale_rules);
addEndpoint(update_price_automation_sale_rules);
addEndpoint(list_price_automation_sale_rules);
addEndpoint(delete_price_automation_sale_rules);
addEndpoint(retrieve_rules_price_automation_sale_offers);
addEndpoint(retrieve_sale_categories);
addEndpoint(list_sale_categories);
addEndpoint(retrieve_parameters_sale_categories);
addEndpoint(retrieve_product_parameters_sale_categories);
addEndpoint(create_sale_shipping_rates);
addEndpoint(retrieve_sale_shipping_rates);
addEndpoint(update_sale_shipping_rates);
addEndpoint(list_sale_shipping_rates);
addEndpoint(retrieve_sale_delivery_settings);
addEndpoint(update_sale_delivery_settings);
addEndpoint(create_sale_offer_contacts);
addEndpoint(retrieve_sale_offer_contacts);
addEndpoint(update_sale_offer_contacts);
addEndpoint(list_sale_offer_contacts);
addEndpoint(create_sale_responsible_persons);
addEndpoint(update_sale_responsible_persons);
addEndpoint(list_sale_responsible_persons);
addEndpoint(create_sale_responsible_producers);
addEndpoint(retrieve_sale_responsible_producers);
addEndpoint(update_sale_responsible_producers);
addEndpoint(list_sale_responsible_producers);
addEndpoint(create_sale_size_tables);
addEndpoint(retrieve_sale_size_tables);
addEndpoint(update_sale_size_tables);
addEndpoint(list_sale_size_tables);
addEndpoint(create_sale_offer_variants);
addEndpoint(retrieve_sale_offer_variants);
addEndpoint(update_sale_offer_variants);
addEndpoint(list_sale_offer_variants);
addEndpoint(delete_sale_offer_variants);
addEndpoint(create_sale_offer_attachments);
addEndpoint(retrieve_sale_offer_attachments);
addEndpoint(upload_sale_offer_attachments);
addEndpoint(retrieve_sale_disputes);
addEndpoint(list_sale_disputes);
addEndpoint(create_disputes_sale_messages);
addEndpoint(list_disputes_sale_messages);
addEndpoint(create_sale_dispute_attachments);
addEndpoint(retrieve_sale_dispute_attachments);
addEndpoint(upload_sale_dispute_attachments);
addEndpoint(retrieve_sale_products);
addEndpoint(list_sale_products);
addEndpoint(create_products_sale_change_proposals);
addEndpoint(retrieve_products_sale_change_proposals);
addEndpoint(list_sale_compatibility_list);
addEndpoint(list_sale_compatible_products);
addEndpoint(list_groups_sale_compatible_products);
addEndpoint(list_sale_badges);
addEndpoint(apply_sale_badges);
addEndpoint(update_campaign_badges_sale_offers);
addEndpoint(retrieve_sale_badge_applications);
addEndpoint(list_sale_badge_applications);
addEndpoint(retrieve_sale_allegro_prices_offer_consents);
addEndpoint(update_sale_allegro_prices_offer_consents);
addEndpoint(list_campaigns_sale_alle_discount);
addEndpoint(list_eligible_offers_sale_alle_discount);
addEndpoint(list_submitted_offers_sale_alle_discount);
addEndpoint(create_alle_discount_sale_submit_offer_commands);
addEndpoint(retrieve_alle_discount_sale_submit_offer_commands);
addEndpoint(create_alle_discount_sale_withdraw_offer_commands);
addEndpoint(retrieve_alle_discount_sale_withdraw_offer_commands);
addEndpoint(list_offers);
addEndpoint(change_price_offers);
addEndpoint(retrieve_ratings_summary_users);
addEndpoint(retrieve_me);
addEndpoint(calculate_fee_preview_pricing);
addEndpoint(get_offer_quotes_pricing);
addEndpoint(create_points_of_service);
addEndpoint(retrieve_points_of_service);
addEndpoint(update_points_of_service);
addEndpoint(list_points_of_service);
addEndpoint(delete_points_of_service);
addEndpoint(create_after_sales_service_conditions_return_policies);
addEndpoint(retrieve_after_sales_service_conditions_return_policies);
addEndpoint(update_after_sales_service_conditions_return_policies);
addEndpoint(list_after_sales_service_conditions_return_policies);
addEndpoint(delete_after_sales_service_conditions_return_policies);
addEndpoint(create_after_sales_service_conditions_implied_warranties);
addEndpoint(retrieve_after_sales_service_conditions_implied_warranties);
addEndpoint(update_after_sales_service_conditions_implied_warranties);
addEndpoint(list_after_sales_service_conditions_implied_warranties);
addEndpoint(create_after_sales_service_conditions_warranties);
addEndpoint(retrieve_after_sales_service_conditions_warranties);
addEndpoint(update_after_sales_service_conditions_warranties);
addEndpoint(list_after_sales_service_conditions_warranties);
addEndpoint(create_after_sales_service_conditions_attachments);
addEndpoint(upload_after_sales_service_conditions_attachments);
addEndpoint(get_event_stats_order);
addEndpoint(list_events_order);
addEndpoint(retrieve_order_checkout_forms);
addEndpoint(list_order_checkout_forms);
addEndpoint(update_fulfillment_order_checkout_forms);
addEndpoint(list_checkout_forms_order_shipments);
addEndpoint(add_checkout_forms_order_shipments);
addEndpoint(create_checkout_forms_order_invoices);
addEndpoint(list_checkout_forms_order_invoices);
addEndpoint(upload_file_checkout_forms_order_invoices);
addEndpoint(list_order_carriers);
addEndpoint(get_tracking_order_carriers);
addEndpoint(list_points_carriers_order_allegro);
addEndpoint(create_order_refund_claims);
addEndpoint(retrieve_order_refund_claims);
addEndpoint(list_order_refund_claims);
addEndpoint(cancel_order_refund_claims);
addEndpoint(retrieve_order_customer_returns);
addEndpoint(list_order_customer_returns);
addEndpoint(reject_refund_order_customer_returns);
addEndpoint(create_account_additional_emails);
addEndpoint(retrieve_account_additional_emails);
addEndpoint(list_account_additional_emails);
addEndpoint(delete_account_additional_emails);
addEndpoint(list_operations_payments);
addEndpoint(create_payments_refunds);
addEndpoint(list_payments_refunds);
addEndpoint(retrieve_offers_bidding_bid);
addEndpoint(place_offers_bidding_bid);
addEndpoint(list_billing_entries_billing);
addEndpoint(list_billing_types_billing);
addEndpoint(list_fundraising_campaigns_charity);
addEndpoint(create_label_shipment_management);
addEndpoint(create_protocol_shipment_management);
addEndpoint(list_delivery_services_shipment_management);
addEndpoint(list_pickup_proposals_shipment_management);
addEndpoint(retrieve_shipment_management_shipments);
addEndpoint(create_shipments_shipment_management_create_commands);
addEndpoint(get_status_shipments_shipment_management_create_commands);
addEndpoint(cancel_shipments_shipment_management_cancel_commands);
addEndpoint(get_status_shipments_shipment_management_cancel_commands);
addEndpoint(get_status_pickups_shipment_management_create_commands);
addEndpoint(request_pickup_pickups_shipment_management_create_commands);
addEndpoint(list_marketplaces);
addEndpoint(retrieve_messaging_threads);
addEndpoint(list_messaging_threads);
addEndpoint(mark_as_read_messaging_threads);
addEndpoint(create_threads_messaging_messages);
addEndpoint(list_threads_messaging_messages);
addEndpoint(create_messaging_messages);
addEndpoint(retrieve_messaging_messages);
addEndpoint(delete_messaging_messages);
addEndpoint(create_messaging_message_attachments);
addEndpoint(download_messaging_message_attachments);
addEndpoint(upload_messaging_message_attachments);
addEndpoint(get_available_products_fulfillment);
addEndpoint(get_stock_fulfillment);
addEndpoint(create_fulfillment_advance_ship_notices);
addEndpoint(retrieve_fulfillment_advance_ship_notices);
addEndpoint(update_fulfillment_advance_ship_notices);
addEndpoint(list_fulfillment_advance_ship_notices);
addEndpoint(delete_fulfillment_advance_ship_notices);
addEndpoint(cancel_fulfillment_advance_ship_notices);
addEndpoint(get_labels_fulfillment_advance_ship_notices);
addEndpoint(get_receiving_state_fulfillment_advance_ship_notices);
addEndpoint(update_submitted_fulfillment_advance_ship_notices);
addEndpoint(get_status_fulfillment_submit_commands);
addEndpoint(submit_fulfillment_submit_commands);
addEndpoint(get_parcels_fulfillment_orders);
addEndpoint(update_fulfillment_tax_id);
addEndpoint(add_fulfillment_tax_id);
addEndpoint(get_fulfillment_tax_id);
addEndpoint(create_removal_fulfillment_preferences);
addEndpoint(get_removal_fulfillment_preferences);

export type Filter = {
  type: 'resource' | 'operation' | 'tag' | 'tool';
  op: 'include' | 'exclude';
  value: string;
};

export function query(filters: Filter[], endpoints: Endpoint[]): Endpoint[] {
  const allExcludes = filters.length > 0 && filters.every((filter) => filter.op === 'exclude');
  const unmatchedFilters = new Set(filters);

  const filtered = endpoints.filter((endpoint: Endpoint) => {
    let included = false || allExcludes;

    for (const filter of filters) {
      if (match(filter, endpoint)) {
        unmatchedFilters.delete(filter);
        included = filter.op === 'include';
      }
    }

    return included;
  });

  // Check if any filters didn't match
  const unmatched = Array.from(unmatchedFilters).filter((f) => f.type === 'tool' || f.type === 'resource');
  if (unmatched.length > 0) {
    throw new Error(
      `The following filters did not match any endpoints: ${unmatched
        .map((f) => `${f.type}=${f.value}`)
        .join(', ')}`,
    );
  }

  return filtered;
}

function match({ type, value }: Filter, endpoint: Endpoint): boolean {
  switch (type) {
    case 'resource': {
      const regexStr = '^' + normalizeResource(value).replace(/\*/g, '.*') + '$';
      const regex = new RegExp(regexStr);
      return regex.test(normalizeResource(endpoint.metadata.resource));
    }
    case 'operation':
      return endpoint.metadata.operation === value;
    case 'tag':
      return endpoint.metadata.tags.includes(value);
    case 'tool':
      return endpoint.tool.name === value;
  }
}

function normalizeResource(resource: string): string {
  return resource.toLowerCase().replace(/[^a-z.*\-_]*/g, '');
}
