// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { asTextContentResult } from 'allegro-api-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import type { Metadata } from '../';
import AllegroAPI from 'allegro-api';

export const metadata: Metadata = {
  resource: 'offers',
  operation: 'write',
  tags: [],
  httpMethod: 'put',
  httpPath: '/offers/{offerId}/change-price-commands/{commandId}',
  operationId: 'createChangePriceCommandUsingPUT',
};

export const tool: Tool = {
  name: 'change_price_offers',
  description:
    'Use this resource to change the Buy Now price in a single offer. Read more: <a href="../../news/mozliwosc-zmiany-ceny-kup-teraz-2YzrKRrr3Sl" target="_blank">PL</a> / <a href="../../news/possibility-to-change-the-buy-it-now-price-q018mq8D2hW" target="_blank">EN</a>.',
  inputSchema: {
    type: 'object',
    properties: {
      offerId: {
        type: 'string',
      },
      commandId: {
        type: 'string',
      },
      input: {
        $ref: '#/$defs/change_price_input',
      },
      id: {
        type: 'string',
        description:
          'The unique command id generated by you. This should be the same UUID as used in the path.',
      },
    },
    $defs: {
      change_price_input: {
        type: 'object',
        description: 'The input of the command, i.e. the new Buy Now price for the offer.',
        properties: {
          buyNowPrice: {
            $ref: '#/$defs/price',
          },
        },
        required: ['buyNowPrice'],
      },
      price: {
        type: 'object',
        description: 'The price data.',
        properties: {
          amount: {
            type: 'string',
            description: 'The amount provided in a string format to avoid rounding errors.',
          },
          currency: {
            type: 'string',
            description:
              'The currency provided as a 3-letter code in accordance with ISO 4217 standard (https://en.wikipedia.org/wiki/ISO_4217).',
          },
        },
        required: ['amount', 'currency'],
      },
    },
  },
};

export const handler = async (client: AllegroAPI, args: Record<string, unknown> | undefined) => {
  const { commandId, ...body } = args as any;
  return asTextContentResult(await client.offers.changePrice(commandId, body));
};

export default { metadata, tool, handler };
